// <auto-generated />
namespace MovieMeter.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_double_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_double_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201709151951119_removed_double_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
